#!/bin/bash
set -e -x

sudo apt-get -y install python3-pip
pip3 install linux-metrics
pip3 install kafka-python

sudo apt-get -y install libpq-dev
pip3 install psycopg2

# Development use
# sudo apt install postgresql-client

